# Generated by Django 5.2.11 on 2026-02-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nper', models.IntegerField()),
                ('sigla', models.CharField(max_length=10)),
            ],
        ),
    ]
