# Generated by Django 5.2.6 on 2026-02-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculadora', '0002_calculo_tipo_transformacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porcentaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
            ],
        ),
    ]
